site:
  url: https://www.reactivepriciples.org
  title: The Reactive Principles
  
content:
  branches: [HEAD]
  sources:
  - url:  git@github.com:reactivemanifesto/reactive-principles.git
    edit_url: ~
    start-path: docs
  
ui:
  bundle:
    url: ./antora-ui-default-rp-src/build/ui-rp-theme-bundle.zip
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll

runtime:
  fetch: true

asciidoc:
  attributes:
    
    page-pagination: ""
    page-toctitle: "On This Page"
    
output:
   dir: ./build
   clean: true
