site:
  url: https://www.reactivepriciples.org
  title: The Reactive Principles
  
content:
  branches: [HEAD]
  sources:
  - url:  git@github.com:reactivemanifesto/reactive-principles.git
    edit_url: ~
    start-path: docs
  
ui:
  bundle:
    url: ./antora-ui-default-rp-src-antora-3/antora-ui-default-master/build/ui-bundle.zip

antora:
  extensions:
  - '@antora/lunr-extension'

runtime:
  fetch: true

asciidoc:
  attributes:
    page-pagination: ""
    page-toctitle: "On This Page"
    
output:
   dir: ./build/site
   clean: true