name: "Generate site and doc search index using antora site action"
uses: kameshsampath/antora-site-action@v0.3.0
with:
    antora_playbook: playbook.yml
    # optional path within the repo, defaults to ${{github.workspace}}
    site_sources_path: 'docs'
    antora_generator: 'antora-site-generator-lunr'
    antora_docsearch_enabled: 'true'
